### ISSUE TITLE
默认头像不显示

### ISSUE THREAD

**Issue by zyjqjnh** [halo-dev/halo-comment#10]
默认头像不显示
api/content/options/comment  返回
{"status":200,"message":"OK","devMessage":null,"data":{"comment_gravatar_default":"mm"}}
但是参数d是undefined 
src="//cn.gravatar.com/avatar?d=undefined"

**Comment by ruibaby** [comment]
@zyjqjnh 已知bug，下个版本修复。

**Comment by ruibaby** [comment]
已修复。
