### ISSUE TITLE
我发现另一个问题， 评论时不能输入空格

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo-comment#18]
我发现另一个问题， 评论时不能输入空格

_Originally posted by @zhaokuohaha in https://github.com/halo-dev/halo-theme-material/issues/2#issuecomment-531462815_

**Comment by zhaokuohaha** [comment]
@ruibaby  感觉是主题的锅, 我试了下其他主题没有这个问题

**Comment by ruibaby** [comment]
> @ruibaby 感觉是主题的锅, 我试了下其他主题没有这个问题

有可能是主题的一些特性影响的

**Comment by ruibaby** [comment]
经过测试，是 smoothscroll.js 这个插件导致的，如果对你没用，你可以在主题设置的 `其他设置` 关闭 `平滑滚动效果`。

另外，我今天下午将 Material 主题重新做了一遍，稍后提交发布。

**Comment by zhaokuohaha** [comment]
关掉平滑滚动解决了
