### ISSUE TITLE
评论模块bug反馈（轻微，影响用户体验）

### ISSUE THREAD

**Issue by andglf** [halo-dev/halo-comment#22]
![Y06%JU531GWP{`}X Q9P6I4](https://user-images.githubusercontent.com/46335954/70605161-e7241480-1c34-11ea-9a2e-f80d8f083288.png)
在第一次评论的时候，需要录入必填信息才可以正常进行评论，如图中前两个字段，最后一个博客地址是不需要写的，但是如果第一次不写的话，下次再进行评论的时候，这个地方的默认值就是null，导致不能正常评论，必须要手动把null删除或者写上正确的网址，才可以正常评论

**Comment by ruibaby** [comment]
@andglf 这是设定。不是bug。如果你有好的想法 可以提出来

**Comment by andglf** [comment]
@ruibaby 刚刚没写完，现在修改了，你重新看一下

**Comment by ruibaby** [comment]
@andglf 好的，明白了

**Comment by johnhorse** [comment]
//cdn.v2ex.com/gravatar  这个地址是什么？  我这需要翻墙才能拿到头像图片。。。

**Comment by ruibaby** [comment]
@johnhorse gravatar 源地
