### ISSUE TITLE
请问为什么修改了代码之后，打包之后，halo中引用却不生效?

### ISSUE THREAD

**Issue by xebcxc** [halo-dev/halo-comment#25]
修改了部分代码，使用`npm run build-comment`打包之后，生成了单独的halo-comment.min.js。项目中引用这个js，修改的代码却不生效。

**Comment by ruibaby** [comment]
@xebcxc 看一下你的相关代码

**Comment by xebcxc** [comment]
> @xebcxc 看一下你的相关代码


![image](https://user-images.githubusercontent.com/23736683/70994035-4340da00-2108-11ea-9889-d80dc7c0c1f1.png)

![image](https://user-images.githubusercontent.com/23736683/70994095-67042000-2108-11ea-94ed-e5026324d34e.png)

**Comment by ruibaby** [comment]
> > @xebcxc 看一下你的相关代码
> 
> ![image](https://user-images.githubusercontent.com/23736683/70994035-4340da00-2108-11ea-9889-d80dc7c0c1f1.png)
> 
> ![image](https://user-images.githubusercontent.com/23736683/70994095-67042000-2108-11ea-94ed-e5026324d34e.png)

怎么引用的呢？

**Comment by xebcxc** [comment]
> > > @xebcxc 看一下你的相关代码
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/23736683/70994035-4340da00-2108-11ea-9889-d80dc7c0c1f1.png)
> > ![image](https://user-images.githubusercontent.com/23736683/70994095-67042000-2108-11ea-94ed-e5026324d34e.png)
> 
> 怎么引用的呢？

![image](https://user-images.githubusercontent.com/23736683/70994469-47212c00-2109-11ea-9a5e-e00eadd8aedc.png)

我是打包放到本地，本地直接引用的

**Comment by ruibaby** [comment]
建议 F12 查看一下 js 的请求地址是否正确。

**Comment by xebcxc** [comment]
> 建议 F12 查看一下 js 的请求地址是否正确。

![image](https://user-images.githubusercontent.com/23736683/70994805-f52cd600-2109-11ea-8812-41401ee965c8.png)

确实请求地址不对，但是我也没有在代码中找到对应引用这个文件的地方呀

**Comment by xebcxc** [comment]
> 建议 F12 查看一下 js 的请求地址是否正确。

看到了，后台有配置，谢谢大佬
![image](https://user-images.githubusercontent.com/23736683/70996782-78502b00-210e-11ea-878b-239d0c226724.png)

**Comment by ruibaby** [comment]
哦，不好意思，刚刚没有仔细看。

```diff
-<script src="${options.comment_internal_plugin_js!'//cdn.jsdelivr.net/gh/halo-dev/halo-comment@latest/dist/halo-comment.min.js'}"></script>
+<script src="/plugins/halo-comment/halo-comment.min.js"></script>
```

**Comment by xebcxc** [comment]
> 哦，不好意思，刚刚没有仔细看。
> 
> ```diff
> -<script src="${options.comment_internal_plugin_js!'//cdn.jsdelivr.net/gh/halo-dev/halo-comment@latest/dist/halo-comment.min.js'}"></script>
> +<script src="/plugins/halo-comment/halo-comment.min.js"></script>
> ```

我就是改了这个地方，我去后台上传了一个文件，改了博客设置就没有改这个地方了
谢谢解答

**Comment by ruibaby** [comment]
@xebcxc 也可以
