### ISSUE TITLE
Issue when building comment module

### ISSUE THREAD

**Issue by salahatwa** [halo-dev/halo-comment#42]
i tried build comment module and received below error 

![image](https://user-images.githubusercontent.com/11550708/106366576-7878ad80-6345-11eb-9c6f-0c40e72fd049.png)

**Comment by ruibaby** [comment]
I don’t have a windows device,  You can try to compile on wsl.

**Comment by salahatwa** [comment]
what's wsl , it's linux ?

**Comment by ruibaby** [comment]
> what's wsl , it's linux ?

Linux on Windows, Available for download in Microsoft Store.

**Comment by salahatwa** [comment]
thanks
