### ISSUE TITLE
咨询Halo评论模块的邮箱作用

### ISSUE THREAD

**Issue by hellxz** [halo-dev/halo-comment#59]
Halo的开发伙伴们你们好啊，咨询Halo评论模块的必填项邮箱作用是什么？

是标识用户，还是会评论/回复发送邮件吗？

**Comment by ruibaby** [comment]
主要用于 Gravatar 头像以及通知。不过已经在考虑取消必填了。

https://github.com/halo-dev/halo/issues/1369

**Comment by hellxz** [comment]
好的，感谢回复，既然已经有issue提了，这边就关闭了。
