### ISSUE TITLE
建议更新头像js

### ISSUE THREAD

**Issue by boluofan** [halo-dev/halo-comment#65]
现在项目引用的halo-comment.min.js中头像cdn地址异常，无法成功获取头像
![image](https://user-images.githubusercontent.com/40459801/148874957-0fd0b801-8d7c-430c-b4bc-6ba4a55103fe.png)

![image](https://user-images.githubusercontent.com/40459801/148875254-822baf5a-f8c0-480c-9a47-ec8711d181a9.png)
建议将`//cn.gravatar.com/avatar/`换成 `//dn-qiniu-avatar.qbox.me/avatar/` 
测试可用

**Comment by ruibaby** [comment]
目前在 Halo 后台可以设置。

**Comment by boluofan** [comment]
收到 666
